#include "../../include/wasm_transpiler.h"
#include <iostream>
#include <algorithm>
#include <sstream>
#include <iomanip>

// ========================================
// Helper Methods
// ========================================

void WasmTranspiler::indent() {
    for (int i = 0; i < indentLevel; ++i) {
        output << "  ";
    }
}

void WasmTranspiler::emit(const std::string& code) {
    output << code;
}

void WasmTranspiler::emitLine(const std::string& code) {
    indent();
    output << code << "\n";
}

int WasmTranspiler::getLocalIndex(const std::string& name) {
    auto it = localVariables.find(name);
    if (it != localVariables.end()) {
        return it->second;
    }
    int index = nextLocalIndex++;
    localVariables[name] = index;
    return index;
}

int WasmTranspiler::alignUp(int offset, int alignment) {
    return ((offset + alignment - 1) / alignment) * alignment;
}

int WasmTranspiler::allocateString(const std::string& str) {
    // Align to 4-byte boundary
    int offset = alignUp(stringDataOffset, 4);
    stringLiterals.push_back({offset, str});
    // 4 bytes for length + string bytes + null terminator
    stringDataOffset = offset + 4 + static_cast<int>(str.length());
    return offset;
}

int WasmTranspiler::allocateHeapBlock(int size) {
    // Align size to 8-byte boundary
    size = alignUp(size, ALIGNMENT);
    int ptr = heapPointer;
    heapPointer += size;
    return ptr;
}

std::string WasmTranspiler::escapeStringForWat(const std::string& str) {
    std::string result;
    for (char c : str) {
        switch (c) {
            case '"': result += "\\\""; break;
            case '\\': result += "\\\\"; break;
            case '\n': result += "\\n"; break;
            case '\r': result += "\\r"; break;
            case '\t': result += "\\t"; break;
            default:
                if (c >= 32 && c < 127) {
                    result += c;
                } else {
                    std::ostringstream oss;
                    oss << "\\" << std::setfill('0') << std::setw(2) << std::hex << static_cast<int>(static_cast<unsigned char>(c));
                    result += oss.str();
                }
        }
    }
    return result;
}

std::string WasmTranspiler::stringToWatHex(const std::string& str) {
    std::string result;
    for (unsigned char c : str) {
        std::ostringstream oss;
        oss << std::setfill('0') << std::setw(2) << std::hex << static_cast<int>(c);
        result += "\\" + oss.str();
    }
    return result;
}

// ========================================
// Main Transpile Function
// ========================================

std::string WasmTranspiler::transpile(const std::vector<std::unique_ptr<Statement>>& statements) {
    // Reset state
    stringLiterals.clear();
    structFields.clear();
    structSizes.clear();
    variableTypes.clear();
    stringDataOffset = 0;
    heapPointer = 1024;

    // WAT module header
    output << ";; Generated by SynthFlow WebAssembly Transpiler\n";
    output << ";; SynthFlow v0.0.30\n\n";
    output << "(module\n";
    indentLevel++;

    // Import print functions from host environment
    emitLine(";; Import print functions from JavaScript host");
    emitLine("(import \"env\" \"print_f64\" (func $print_f64 (param f64)))");
    emitLine("(import \"env\" \"print_i32\" (func $print_i32 (param i32)))");
    emitLine("(import \"env\" \"print_string\" (func $print_string (param i32 i32)))");  // ptr, len
    emitLine("(import \"env\" \"print_char\" (func $print_char (param i32)))");  // char code
    emitLine("");

    // Memory for strings and arrays (2 pages = 128KB)
    emitLine(";; Linear memory for strings, arrays, maps, and structs");
    emitLine("(memory (export \"memory\") 2)");
    emitLine("");

    // Memory management globals
    emitLine(";; Heap pointer for dynamic allocation");
    emitLine("(global $heap_ptr (mut i32) (i32.const 1024))");
    emitLine("");

    // First pass: collect struct declarations
    for (const auto& stmt : statements) {
        if (auto* structDecl = dynamic_cast<StructDeclaration*>(stmt.get())) {
            int structSize = 0;
            std::vector<std::pair<std::string, std::string>> fields;
            for (const auto& field : structDecl->fields) {
                fields.push_back({field.name, field.typeName});
                structSize += 8;  // All fields are 8 bytes (f64 or i32 ptr)
            }
            structFields[structDecl->name] = fields;
            structSizes[structDecl->name] = structSize;
        }
    }

    // First pass: collect function declarations
    for (const auto& stmt : statements) {
        if (auto* funcDecl = dynamic_cast<FunctionDeclaration*>(stmt.get())) {
            functionNames.push_back(funcDecl->name);
        }
    }

    // Emit memory management helper functions
    emitLine(";; Memory allocation function - returns pointer to allocated block");
    emitLine("(func $alloc (export \"alloc\") (param $size i32) (result i32)");
    indentLevel++;
    emitLine("(local $ptr i32)");
    emitLine(";; Get current heap pointer");
    emitLine("local.get $heap_ptr");
    emitLine("local.set $ptr");
    emitLine(";; Advance heap pointer by size (aligned to 8 bytes)");
    emitLine("local.get $heap_ptr");
    emitLine("local.get $size");
    emitLine("i32.add");
    emitLine(";; Align to 8 bytes");
    emitLine("i32.const 7");
    emitLine("i32.add");
    emitLine("i32.const -8");
    emitLine("i32.and");
    emitLine("local.set $heap_ptr");
    emitLine(";; Return allocated pointer");
    emitLine("local.get $ptr");
    indentLevel--;
    emitLine("))");
    emitLine("");

    // Emit string length helper
    emitLine(";; Get string length from string pointer");
    emitLine(";; String format: [length: i32][chars...]");
    emitLine("(func $string_length (param $ptr i32) (result i32)");
    indentLevel++;
    emitLine("local.get $ptr");
    emitLine("i32.load");
    indentLevel--;
    emitLine("))");
    emitLine("");

    // Emit array operations
    emitLine(";; Array element access");
    emitLine(";; Array format: [length: i32][elem_size: i32][element0][element1]...");
    emitLine("(func $array_get (param $arr_ptr i32) (param $index i32) (param $elem_size i32) (result f64)");
    indentLevel++;
    emitLine(";; Calculate offset: arr_ptr + 8 (header) + index * elem_size");
    emitLine("local.get $arr_ptr");
    emitLine("i32.const 8");
    emitLine("i32.add");
    emitLine("local.get $index");
    emitLine("local.get $elem_size");
    emitLine("i32.mul");
    emitLine("i32.add");
    emitLine("f64.load");
    indentLevel--;
    emitLine("))");
    emitLine("");

    emitLine(";; Array element set");
    emitLine("(func $array_set (param $arr_ptr i32) (param $index i32) (param $elem_size i32) (param $value f64)");
    indentLevel++;
    emitLine("local.get $arr_ptr");
    emitLine("i32.const 8");
    emitLine("i32.add");
    emitLine("local.get $index");
    emitLine("local.get $elem_size");
    emitLine("i32.mul");
    emitLine("i32.add");
    emitLine("local.get $value");
    emitLine("f64.store");
    indentLevel--;
    emitLine("))");
    emitLine("");

    // Generate code for each statement - functions and structs first
    for (const auto& stmt : statements) {
        if (dynamic_cast<FunctionDeclaration*>(stmt.get()) ||
            dynamic_cast<StructDeclaration*>(stmt.get())) {
            stmt->accept(*this);
        }
    }

    // Generate data section for string literals
    if (!stringLiterals.empty()) {
        emitLine("");
        emitLine(";; String literal data section");
        for (const auto& [offset, str] : stringLiterals) {
            std::ostringstream dataLine;
            dataLine << "(data (i32.const " << offset << ") \"";
            // Store length as little-endian 32-bit integer
            uint32_t len = static_cast<uint32_t>(str.length());
            dataLine << "\\"
                     << std::setfill('0') << std::setw(2) << std::hex << (len & 0xFF)
                     << "\\"
                     << std::setw(2) << std::hex << ((len >> 8) & 0xFF)
                     << "\\"
                     << std::setw(2) << std::hex << ((len >> 16) & 0xFF)
                     << "\\"
                     << std::setw(2) << std::hex << ((len >> 24) & 0xFF);
            dataLine << stringToWatHex(str);
            dataLine << "\")";
            emitLine(dataLine.str());
        }
    }

    // Generate $main function that contains all top-level code
    emitLine("");
    emitLine(";; Main entry point - contains all top-level code");
    emitLine("(func (export \"main\")");
    indentLevel++;

    // Add temp locals for array/map operations in main
    emitLine("(local $__arr_ptr i32)  ;; temp for array operations");
    emitLine("(local $__arr_idx i32)  ;; temp for array index");
    emitLine("(local $__arr_val f64)  ;; temp for array value");
    emitLine("(local $__map_ptr i32)  ;; temp for map operations");
    emitLine("(local $__match_val f64)  ;; temp for match expression");

    // Generate top-level statements (variables, expressions, etc.)
    inFunction = true;
    for (const auto& stmt : statements) {
        if (!dynamic_cast<FunctionDeclaration*>(stmt.get()) &&
            !dynamic_cast<StructDeclaration*>(stmt.get())) {
            stmt->accept(*this);
        }
    }
    inFunction = false;

    indentLevel--;
    emitLine(")");
        }
    }
    if (hasStart) {
        for (const auto& name : functionNames) {
            if (name == "_start" || name == "main") {
                emitLine("(call $" + name + ") drop");
                break;
            }
        }
    }

    indentLevel--;
    emitLine(")");

    indentLevel--;
    output << ")\n";

    return output.str();
}

// ========================================
// Expression Visitors
// ========================================

void WasmTranspiler::visit(IntegerLiteral* node) {
    emit("(f64.const " + std::to_string(static_cast<double>(node->value)) + ")");
}

void WasmTranspiler::visit(FloatLiteral* node) {
    emit("(f64.const " + std::to_string(node->value) + ")");
}

void WasmTranspiler::visit(StringLiteral* node) {
    // Allocate string literal and return pointer
    int offset = allocateString(node->value);
    emit("(i32.const " + std::to_string(offset) + ") ;; string: \"" + escapeStringForWat(node->value) + "\"");
}

void WasmTranspiler::visit(BooleanLiteral* node) {
    emit(node->value ? "(f64.const 1)" : "(f64.const 0)");
}

void WasmTranspiler::visit(NullLiteral* node) {
    (void)node;
    emit("(i32.const 0) ;; null pointer");
}

void WasmTranspiler::visit(Identifier* node) {
    // Check if this is a struct variable for type tracking
    if (variableTypes.count(node->name)) {
        emit("(local.get $" + node->name + ") ;; " + node->name + ": " + variableTypes[node->name]);
    } else {
        emit("(local.get $" + node->name + ")");
    }
}

void WasmTranspiler::visit(BinaryExpression* node) {
    std::string op = node->op;

    // Handle string concatenation
    if (op == "+" && dynamic_cast<StringLiteral*>(node->left.get())) {
        // String concatenation - for now, just return left pointer
        // TODO: Implement proper string concatenation with new allocation
        node->left->accept(*this);
        emit(" ;; string concat (TODO: proper implementation)");
        return;
    }

    // Emit operands first (stack-based)
    node->left->accept(*this);
    emit(" ");
    node->right->accept(*this);
    emit(" ");

    // Then emit the operation
    if (op == "+") emit("(f64.add)");
    else if (op == "-") emit("(f64.sub)");
    else if (op == "*") emit("(f64.mul)");
    else if (op == "/") emit("(f64.div)");
    else if (op == "%") {
        // Modulo: use rem instruction for f64
        // Stack: a b -> a % b
        // We need to be careful - save values first
        // Actually, we can use the stack directly:
        // a b f64.rem
        emit("(f64.rem)");
    }
    else if (op == "==" || op == "!=") {
        emit(op == "==" ? "(f64.eq)" : "(f64.ne)");
    }
    else if (op == "<") emit("(f64.lt)");
    else if (op == "<=") emit("(f64.le)");
    else if (op == ">") emit("(f64.gt)");
    else if (op == ">=") emit("(f64.ge)");
    else if (op == "&&" || op == "and") {
        // Convert f64 to i32 for logical ops
        // Left operand is f64, right is f64
        // (f64.ne (f64.const 0)) converts f64 to i32 bool
        emit("(f64.const 0) (f64.ne) ");  // left -> i32 bool
        emit("(f64.const 0) (f64.ne) ");  // right -> i32 bool
        emit("i32.and (if (result f64) (then (f64.const 1)) (else (f64.const 0)))");
    }
    else if (op == "||" || op == "or") {
        emit("(f64.const 0) (f64.ne) ");
        emit("(f64.const 0) (f64.ne) ");
        emit("i32.or (if (result f64) (then (f64.const 1)) (else (f64.const 0)))");
    }
    else {
        emit(";; unsupported op: " + op);
    }
}

void WasmTranspiler::visit(UnaryExpression* node) {
    std::string op = node->op;
    node->operand->accept(*this);

    if (op == "-") {
        emit(" (f64.neg)");
    } else if (op == "!" || op == "not") {
        emit(" (f64.const 0) (f64.eq) (if (result f64) (then (f64.const 1)) (else (f64.const 0)))");
    }
}

void WasmTranspiler::visit(AssignmentExpression* node) {
    // Get the variable name from left side
    if (auto* id = dynamic_cast<Identifier*>(node->left.get())) {
        node->right->accept(*this);
        emit(" (local.set $" + id->name + ")");
    } else if (auto* memberExpr = dynamic_cast<MemberExpression*>(node->left.get())) {
        // Handle member assignment: obj.field = value
        // For now, simplified - proper implementation needs to track struct offsets
        node->right->accept(*this);
        emit(" ;; member assignment (struct field)");
    }
}

void WasmTranspiler::visit(CallExpression* node) {
    // Handle print specially for strings
    if (node->callee == "print" && !node->arguments.empty()) {
        // Check if first argument is a string literal
        if (auto* strLit = dynamic_cast<StringLiteral*>(node->arguments[0].get())) {
            int offset = allocateString(strLit->value);
            emit("(i32.const " + std::to_string(offset) + ")");
            emit(" (i32.const " + std::to_string(strLit->value.length()) + ")");
            emit(" (call $print_string)");
            return;
        }
    }

    // Emit arguments first
    for (const auto& arg : node->arguments) {
        arg->accept(*this);
        emit(" ");
    }

    // Handle built-in functions
    if (node->callee == "print") {
        emit("(call $print_f64)");
    } else if (node->callee == "len" || node->callee == "length") {
        // Length function - assumes i32 pointer to array/string
        emit("(i32.load) ;; get length from pointer");
    } else if (node->callee == "alloc") {
        emit("(call $alloc)");
    } else {
        emit("(call $" + node->callee + ")");
    }
}

void WasmTranspiler::visit(ArrayLiteral* node) {
    // Allocate array in linear memory
    // Format: [length: i32][element_size: i32][element0: f64][element1: f64]...
    int numElements = static_cast<int>(node->elements.size());
    int arraySize = 8 + (numElements * 8);  // header (8 bytes) + elements (8 bytes each)

    emit("\n");
    indent();
    emit(";; Array literal with " + std::to_string(numElements) + " elements\n");

    // Allocate memory for array
    indent();
    emit("(call $alloc (i32.const " + std::to_string(arraySize) + "))\n");

    // Store the array pointer in a temp local
    emit("(local.set $__arr_ptr)\n");
    indent();
    emit("(local.get $__arr_ptr)\n");

    // Store length
    indent();
    emit("i32.const " + std::to_string(numElements) + "\n");
    indent();
    emit("i32.store\n");

    // Store element size (8 for f64)
    indent();
    emit("(local.get $__arr_ptr)\n");
    indent();
    emit("i32.const 4\n");
    indent();
    emit("i32.add\n");  // offset to element_size field
    indent();
    emit("i32.const 8\n");  // element size = 8 bytes (f64)
    indent();
    emit("i32.store\n");

    // Store each element
    for (int i = 0; i < numElements; i++) {
        indent();
        emit("(local.get $__arr_ptr)\n");
        indent();
        emit("i32.const " + std::to_string(8 + i * 8) + "\n");  // offset to element
        indent();
        emit("i32.add\n");
        node->elements[i]->accept(*this);
        emit("\n");
        indent();
        emit("f64.store\n");
    }

    // Return array pointer
    indent();
    emit("(local.get $__arr_ptr)");
}

void WasmTranspiler::visit(ArrayIndexExpression* node) {
    // Get array pointer and index
    indent();
    node->array->accept(*this);
    emit("\n");
    indent();
    node->index->accept(*this);
    emit("\n");

    // Calculate address: arr_ptr + 8 + index * 8
    indent();
    emit(";; Array index access\n");
    indent();
    emit("(local.set $__arr_idx)\n");  // save index
    indent();
    emit("(local.set $__arr_ptr)\n");  // save array pointer

    indent();
    emit("(local.get $__arr_ptr)\n");
    indent();
    emit("i32.const 8\n");
    indent();
    emit("i32.add\n");  // skip header
    indent();
    emit("(local.get $__arr_idx)\n");
    indent();
    emit("i32.const 8\n");
    indent();
    emit("i32.mul\n");  // index * 8 (element size)
    indent();
    emit("i32.add\n");
    indent();
    emit("f64.load");
}

void WasmTranspiler::visit(ArrayAssignmentExpression* node) {
    // Get array pointer, index, and value
    indent();
    node->array->accept(*this);
    emit("\n");
    indent();
    node->index->accept(*this);
    emit("\n");
    indent();
    node->value->accept(*this);
    emit("\n");

    indent();
    emit(";; Array assignment\n");
    indent();
    emit("(local.set $__arr_val)\n");  // save value
    indent();
    emit("(local.set $__arr_idx)\n");  // save index
    indent();
    emit("(local.set $__arr_ptr)\n");  // save array pointer

    // Calculate address and store
    indent();
    emit("(local.get $__arr_ptr)\n");
    indent();
    emit("i32.const 8\n");
    indent();
    emit("i32.add\n");  // skip header
    indent();
    emit("(local.get $__arr_idx)\n");
    indent();
    emit("i32.const 8\n");
    indent();
    emit("i32.mul\n");  // index * 8
    indent();
    emit("i32.add\n");
    indent();
    emit("(local.get $__arr_val)\n");
    indent();
    emit("f64.store");
}

void WasmTranspiler::visit(LambdaExpression* node) {
    (void)node;
    emit(";; lambda (not yet supported in Wasm target)");
}

void WasmTranspiler::visit(MatchExpression* node) {
    emit(";; match expression - converting to if/else chain\n");
    indent();

    // Get the subject value
    node->subject->accept(*this);
    emit(" (local.set $__match_val)\n");

    // Generate if/else chain for each case
    bool first = true;
    for (const auto& matchCase : node->cases) {
        if (!matchCase.pattern) {
            // Default case
            indent();
            emit("(block $__match_end\n");
            indentLevel++;

            // If all previous cases failed, execute default
            indent();
            matchCase.result->accept(*this);

            indentLevel--;
            indent();
            emit(")\n");
        } else {
            indent();
            if (!first) {
                emit("(else\n");
                indentLevel++;
            }

            // Compare subject with pattern
            emit("(local.get $__match_val) ");
            matchCase.pattern->accept(*this);
            emit(" (f64.eq)\n");

            indent();
            emit("(if\n");
            indentLevel++;
            indent();
            emit("(then\n");
            indentLevel++;

            // Execute the result expression
            indent();
            matchCase.result->accept(*this);
            emit("\n");

            indentLevel--;
            indent();
            emit(")\n");

            first = false;
        }
    }

    // Close all the if/else blocks
    for (size_t i = 0; i < node->cases.size(); i++) {
        if (node->cases[i].pattern) {
            indentLevel--;
            indent();
            emit(")\n");
        }
    }
}

void WasmTranspiler::visit(CompoundAssignment* node) {
    if (auto* id = dynamic_cast<Identifier*>(node->target.get())) {
        emit("(local.get $" + id->name + ") ");
        node->value->accept(*this);

        if (node->op == "+=") emit(" (f64.add)");
        else if (node->op == "-=") emit(" (f64.sub)");
        else if (node->op == "*=") emit(" (f64.mul)");
        else if (node->op == "/=") emit(" (f64.div)");

        emit(" (local.set $" + id->name + ")");
    }
}

void WasmTranspiler::visit(UpdateExpression* node) {
    if (auto* id = dynamic_cast<Identifier*>(node->operand.get())) {
        emit("(local.get $" + id->name + ") (f64.const 1) ");
        emit(node->op == "++" ? "(f64.add)" : "(f64.sub)");
        emit(" (local.set $" + id->name + ")");
    }
}

void WasmTranspiler::visit(InterpolatedString* node) {
    // For now, just allocate the first string part
    // TODO: Implement proper string concatenation
    std::string result;
    for (const auto& part : node->parts) {
        if (!part.isExpression) {
            result += part.text;
        } else {
            result += "${...}";  // Placeholder for expressions
        }
    }

    int offset = allocateString(result);
    emit("(i32.const " + std::to_string(offset) + ") ;; interpolated string");
}

// ========================================
// SADK Expression Visitors
// ========================================

void WasmTranspiler::visit(MapLiteral* node) {
    // Allocate map in linear memory
    // Format: [count: i32][capacity: i32][entries...]
    // Each entry: [key_ptr: i32][key_len: i32][value: f64]
    int numEntries = static_cast<int>(node->entries.size());
    // Map header: count (4) + capacity (4) = 8 bytes
    // Each entry: key_ptr (4) + key_len (4) + value (8) = 16 bytes
    int mapSize = 8 + (numEntries * 16);

    emit("\n");
    indent();
    emit(";; Map literal with " + std::to_string(numEntries) + " entries\n");

    // Allocate memory for map
    indent();
    emit("(call $alloc (i32.const " + std::to_string(mapSize) + "))\n");
    emit("(local.set $__map_ptr)\n");

    // Store count
    indent();
    emit("(local.get $__map_ptr)\n");
    indent();
    emit("i32.const " + std::to_string(numEntries) + "\n");
    indent();
    emit("i32.store\n");

    // Store capacity
    indent();
    emit("(local.get $__map_ptr)\n");
    indent();
    emit("i32.const 4\n");
    indent();
    emit("i32.add\n");
    indent();
    emit("i32.const " + std::to_string(numEntries) + "\n");
    indent();
    emit("i32.store\n");

    // Store each entry
    for (int i = 0; i < numEntries; i++) {
        const auto& entry = node->entries[i];
        int entryOffset = 8 + i * 16;

        // Store key pointer (first evaluate key - should be string)
        indent();
        emit("(local.get $__map_ptr)\n");
        indent();
        emit("i32.const " + std::to_string(entryOffset) + "\n");
        indent();
        emit("i32.add\n");
        entry.first->accept(*this);
        emit("\n");
        indent();
        emit("i32.store\n");

        // Store value
        indent();
        emit("(local.get $__map_ptr)\n");
        indent();
        emit("i32.const " + std::to_string(entryOffset + 8) + "\n");
        indent();
        emit("i32.add\n");
        entry.second->accept(*this);
        emit("\n");
        indent();
        emit("f64.store\n");
    }

    // Return map pointer
    indent();
    emit("(local.get $__map_ptr)");
}

void WasmTranspiler::visit(MemberExpression* node) {
    // Check if object is an identifier and we know its type
    if (auto* id = dynamic_cast<Identifier*>(node->object.get())) {
        std::string varName = id->name;
        std::string varType = variableTypes.count(varName) ? variableTypes[varName] : "";

        // Check if it's a struct we know about
        if (structFields.count(varType)) {
            const auto& fields = structFields[varType];
            int fieldOffset = 0;

            // Find field offset
            for (const auto& field : fields) {
                if (field.first == node->member) {
                    // Found the field
                    indent();
                    emit(";; Accessing " + varType + "." + node->member + " at offset " + std::to_string(fieldOffset) + "\n");
                    indent();
                    emit("(local.get $" + varName + ")\n");
                    indent();
                    emit("i32.const " + std::to_string(fieldOffset) + "\n");
                    indent();
                    emit("i32.add\n");
                    indent();
                    emit("f64.load");
                    return;
                }
                fieldOffset += 8;  // Each field is 8 bytes
            }
        }
    }

    // Fallback: try array.length for arrays
    if (node->member == "length" || node->member == "len") {
        indent();
        node->object->accept(*this);
        emit("\n");
        indent();
        emit("i32.load ;; get array/map length");
        return;
    }

    // Generic member access - just load from offset based on member name hash
    indent();
    emit(";; Member expression: ." + node->member + "\n");
    indent();
    node->object->accept(*this);
    emit("\n");
    indent();
    emit(";; TODO: proper field offset lookup\n");
    indent();
    emit("f64.load");
}

void WasmTranspiler::visit(SelfExpression* node) {
    (void)node;
    emit("(local.get $self) ;; self reference");
}

void WasmTranspiler::visit(MethodCallExpression* node) {
    // Method call: obj.method(args)
    indent();
    emit(";; Method call: " + node->method + "\n");

    // Emit arguments first
    for (const auto& arg : node->arguments) {
        arg->accept(*this);
        emit(" ");
    }

    // Check if this is a known struct method
    if (auto* id = dynamic_cast<Identifier*>(node->object.get())) {
        std::string varName = id->name;
        std::string varType = variableTypes.count(varName) ? variableTypes[varName] : "";

        if (structFields.count(varType)) {
            // This is a struct method call
            emit("(call $" + varType + "_" + node->method + ")");
            return;
        }
    }

    // Generic method call - use naming convention struct_method
    indent();
    node->object->accept(*this);
    emit("\n");
    indent();
    emit("(call $" + node->method + ") ;; generic method call");
}

// ========================================
// Statement Visitors
// ========================================

void WasmTranspiler::visit(VariableDeclaration* node) {
    int idx = getLocalIndex(node->name);

    // Track type for struct variables
    if (!node->typeName.empty()) {
        variableTypes[node->name] = node->typeName;
    }

    indent();

    // Determine the type of the variable
    bool isPointerType = false;
    if (node->typeName == "string" || node->typeName == "String") {
        isPointerType = true;
    } else if (structFields.count(node->typeName)) {
        isPointerType = true;
    } else if (node->initializer) {
        // Check if initializer is a string, array, or map literal
        if (dynamic_cast<StringLiteral*>(node->initializer.get()) ||
            dynamic_cast<ArrayLiteral*>(node->initializer.get()) ||
            dynamic_cast<MapLiteral*>(node->initializer.get())) {
            isPointerType = true;
        }
    }

    if (isPointerType) {
        emit("(local $" + node->name + " i32)");  // Pointer type
    } else {
        emit("(local $" + node->name + " f64)");  // Numeric type
    }

    if (node->initializer) {
        emit(" ");
        node->initializer->accept(*this);
        emit(" (local.set $" + node->name + ")");
    }
    emit("\n");
}

void WasmTranspiler::visit(ExpressionStatement* node) {
    indent();
    node->expression->accept(*this);
    emit("\n");
}

void WasmTranspiler::visit(BlockStatement* node) {
    emitLine("(block");
    indentLevel++;
    for (const auto& stmt : node->statements) {
        stmt->accept(*this);
    }
    indentLevel--;
    emitLine(")");
}

void WasmTranspiler::visit(IfStatement* node) {
    indent();
    node->condition->accept(*this);
    emit("\n");
    emitLine("(if (result f64) (then");
    indentLevel++;
    node->thenBranch->accept(*this);
    indentLevel--;

    if (node->elseBranch) {
        emitLine(") (else");
        indentLevel++;
        node->elseBranch->accept(*this);
        indentLevel--;
        emitLine("))");
    } else {
        emitLine("))");
    }
}

void WasmTranspiler::visit(WhileStatement* node) {
    emitLine("(block $break (result f64)");
    indentLevel++;
    emitLine("(loop $continue");
    indentLevel++;

    // Condition check
    indent();
    node->condition->accept(*this);
    emit(" (i32.trunc_f64_s) (i32.eqz) (br_if $break)\n");

    // Loop body
    node->body->accept(*this);

    emitLine("(br $continue)");
    indentLevel--;
    emitLine(")");
    indentLevel--;
    emitLine(")");
}

void WasmTranspiler::visit(ForStatement* node) {
    // Convert for loop to while loop structure
    emitLine("(block $break (result f64)");
    indentLevel++;

    // Initializer
    if (node->initializer) {
        node->initializer->accept(*this);
    }

    emitLine("(loop $continue");
    indentLevel++;

    // Condition
    if (node->condition) {
        indent();
        node->condition->accept(*this);
        emit(" (i32.trunc_f64_s) (i32.eqz) (br_if $break)\n");
    }

    // Body
    node->body->accept(*this);

    // Increment
    if (node->increment) {
        indent();
        node->increment->accept(*this);
        emit("\n");
    }

    emitLine("(br $continue)");
    indentLevel--;
    emitLine(")");
    indentLevel--;
    emitLine(")");
}

void WasmTranspiler::visit(BreakStatement*) {
    emitLine("(f64.const 0) (br $break)");
}

void WasmTranspiler::visit(ContinueStatement*) {
    emitLine("(br $continue)");
}

void WasmTranspiler::visit(FunctionDeclaration* node) {
    // Reset local variable tracking for new function
    localVariables.clear();
    nextLocalIndex = 0;
    inFunction = true;

    indent();
    emit("(func $" + node->name + " (export \"" + node->name + "\")");

    // Parameters
    for (const auto& param : node->parameters) {
        emit(" (param $" + param + " f64)");
        getLocalIndex(param);
    }

    // Result type (assume f64 for all functions with return)
    emit(" (result f64)");
    emit("\n");

    indentLevel++;

    // Add temp locals for array/map operations
    emitLine("(local $__arr_ptr i32)  ;; temp for array operations");
    emitLine("(local $__arr_idx i32)  ;; temp for array index");
    emitLine("(local $__arr_val f64)  ;; temp for array value");
    emitLine("(local $__map_ptr i32)  ;; temp for map operations");
    emitLine("(local $__match_val f64)  ;; temp for match expression");

    // Function body
    node->body->accept(*this);

    // Default return if not explicit
    emitLine("(f64.const 0)");

    indentLevel--;
    emitLine(")");
    emitLine("");

    inFunction = false;
}

void WasmTranspiler::visit(ReturnStatement* node) {
    indent();
    if (node->value) {
        node->value->accept(*this);
        emit(" ");
    } else {
        emit("(f64.const 0) ");
    }
    emit("(return)\n");
}

void WasmTranspiler::visit(TryStatement* node) {
    // WebAssembly doesn't have native try/catch (in MVP)
    // We emit the try block and add a comment
    emitLine(";; try/catch - executing try block only (Wasm MVP limitation)");
    if (node->tryBlock) {
        node->tryBlock->accept(*this);
    }
}

void WasmTranspiler::visit(ImportStatement* node) {
    // Imports are handled at module level
    emitLine(";; import: " + node->moduleName + (node->alias.empty() ? "" : " as " + node->alias));
}

void WasmTranspiler::visit(StructDeclaration* node) {
    // Struct declarations are processed in the first pass
    // Here we just emit a comment
    int structSize = structSizes.count(node->name) ? structSizes[node->name] : 0;

    emitLine(";; struct " + node->name + " (size: " + std::to_string(structSize) + " bytes)");

    // Emit struct layout comment
    int offset = 0;
    for (const auto& field : node->fields) {
        emitLine(";;   " + field.name + ": " + field.typeName + " @ offset " + std::to_string(offset));
        offset += 8;
    }

    // Emit constructor function
    emitLine("(func $new_" + node->name + " (export \"new_" + node->name + "\") (result i32)");
    indentLevel++;

    // Allocate struct
    emitLine("(local $self i32)");
    emitLine("(call $alloc (i32.const " + std::to_string(structSize) + "))");
    emitLine("(local.set $self)");

    // Initialize fields with defaults
    offset = 0;
    for (const auto& field : node->fields) {
        if (field.defaultValue) {
            emitLine("(local.get $self)");
            emitLine("i32.const " + std::to_string(offset));
            emitLine("i32.add");
            field.defaultValue->accept(*this);
            emit(" f64.store\n");
        } else {
            // Zero-initialize
            emitLine("(local.get $self)");
            emitLine("i32.const " + std::to_string(offset));
            emitLine("i32.add");
            emitLine("(f64.const 0) f64.store");
        }
        offset += 8;
    }

    emitLine("(local.get $self)");
    indentLevel--;
    emitLine(")");

    // Emit methods
    for (const auto& method : node->methods) {
        // Reset local variable tracking
        localVariables.clear();
        nextLocalIndex = 0;

        indent();
        emit("(func $" + node->name + "_" + method->name + " (export \"" + node->name + "." + method->name + "\")");

        // Add self parameter
        emit(" (param $self i32)");

        // Parameters
        for (const auto& param : method->parameters) {
            emit(" (param $" + param + " f64)");
            getLocalIndex(param);
        }

        emit(" (result f64)\n");
        indentLevel++;

        // Add temp locals
        emitLine("(local $__arr_ptr i32)");
        emitLine("(local $__arr_idx i32)");
        emitLine("(local $__arr_val f64)");
        emitLine("(local $__map_ptr i32)");
        emitLine("(local $__match_val f64)");

        // Method body
        method->body->accept(*this);

        emitLine("(f64.const 0)");

        indentLevel--;
        emitLine(")");
        emitLine("");
    }
}