#include "../../include/wasm_transpiler.h"
#include <iostream>

void WasmTranspiler::indent() {
    for (int i = 0; i < indentLevel; ++i) {
        output << "  ";
    }
}

void WasmTranspiler::emit(const std::string& code) {
    output << code;
}

void WasmTranspiler::emitLine(const std::string& code) {
    indent();
    output << code << "\n";
}

int WasmTranspiler::getLocalIndex(const std::string& name) {
    auto it = localVariables.find(name);
    if (it != localVariables.end()) {
        return it->second;
    }
    int index = nextLocalIndex++;
    localVariables[name] = index;
    return index;
}

std::string WasmTranspiler::transpile(const std::vector<std::unique_ptr<Statement>>& statements) {
    // WAT module header
    output << ";; Generated by SynthFlow WebAssembly Transpiler\n";
    output << ";; SynthFlow v0.0.30\n\n";
    output << "(module\n";
    indentLevel++;
    
    // Import print function from host environment
    emitLine(";; Import print function from JavaScript host");
    emitLine("(import \"env\" \"print_f64\" (func $print_f64 (param f64)))");
    emitLine("(import \"env\" \"print_i32\" (func $print_i32 (param i32)))");
    emitLine("");
    
    // Memory for strings (1 page = 64KB)
    emitLine(";; Linear memory for strings and arrays");
    emitLine("(memory (export \"memory\") 1)");
    emitLine("");
    
    // First pass: collect function declarations
    for (const auto& stmt : statements) {
        if (auto* funcDecl = dynamic_cast<FunctionDeclaration*>(stmt.get())) {
            functionNames.push_back(funcDecl->name);
        }
    }
    
    // Generate code for each statement
    for (const auto& stmt : statements) {
        stmt->accept(*this);
    }
    
    // Generate $main function that calls top-level code
    emitLine("");
    emitLine(";; Main entry point");
    emitLine("(func (export \"main\")");
    emitLine("  ;; Call _start if defined, otherwise no-op");
    emitLine(")");
    
    indentLevel--;
    output << ")\n";
    
    return output.str();
}

// ========================================
// Expression Visitors
// ========================================

void WasmTranspiler::visit(IntegerLiteral* node) {
    emit("(f64.const " + std::to_string(static_cast<double>(node->value)) + ")");
}

void WasmTranspiler::visit(FloatLiteral* node) {
    emit("(f64.const " + std::to_string(node->value) + ")");
}

void WasmTranspiler::visit(StringLiteral* node) {
    // Strings are complex in Wasm - emit as i32 pointer for now
    // TODO: Implement proper string handling with memory
    emit("(i32.const 0) ;; string: \"" + node->value + "\"");
}

void WasmTranspiler::visit(BooleanLiteral* node) {
    emit(node->value ? "(f64.const 1)" : "(f64.const 0)");
}

void WasmTranspiler::visit(NullLiteral* node) {
    (void)node;
    emit("(f64.const 0) ;; null");
}

void WasmTranspiler::visit(Identifier* node) {
    int idx = getLocalIndex(node->name);
    emit("(local.get $" + node->name + ")");
}

void WasmTranspiler::visit(BinaryExpression* node) {
    std::string op = node->op;
    
    // Emit operands first (stack-based)
    node->left->accept(*this);
    emit(" ");
    node->right->accept(*this);
    emit(" ");
    
    // Then emit the operation
    if (op == "+") emit("(f64.add)");
    else if (op == "-") emit("(f64.sub)");
    else if (op == "*") emit("(f64.mul)");
    else if (op == "/") emit("(f64.div)");
    else if (op == "%") {
        // Modulo not directly supported, use trunc
        emit("(f64.sub (local.get $__tmp) (f64.mul (f64.trunc (f64.div (local.get $__tmp) (local.get $__tmp2))) (local.get $__tmp2)))");
    }
    else if (op == "==" || op == "!=") {
        emit(op == "==" ? "(f64.eq)" : "(f64.ne)");
    }
    else if (op == "<") emit("(f64.lt)");
    else if (op == "<=") emit("(f64.le)");
    else if (op == ">") emit("(f64.gt)");
    else if (op == ">=") emit("(f64.ge)");
    else if (op == "&&" || op == "and") emit("(i32.and)");
    else if (op == "||" || op == "or") emit("(i32.or)");
    else {
        emit(";; unsupported op: " + op);
    }
}

void WasmTranspiler::visit(UnaryExpression* node) {
    std::string op = node->op;
    node->operand->accept(*this);
    
    if (op == "-") {
        emit(" (f64.neg)");
    } else if (op == "!" || op == "not") {
        emit(" (f64.const 0) (f64.eq)");
    }
}

void WasmTranspiler::visit(AssignmentExpression* node) {
    // Get the variable name from left side
    if (auto* id = dynamic_cast<Identifier*>(node->left.get())) {
        node->right->accept(*this);
        emit(" (local.set $" + id->name + ")");
    }
}

void WasmTranspiler::visit(CallExpression* node) {
    // Emit arguments first
    for (const auto& arg : node->arguments) {
        arg->accept(*this);
        emit(" ");
    }
    
    // Handle built-in functions
    if (node->callee == "print") {
        emit("(call $print_f64)");
    } else {
        emit("(call $" + node->callee + ")");
    }
}

void WasmTranspiler::visit(ArrayLiteral* node) {
    // Arrays require memory management - simplified for MVP
    emit("(i32.const 0) ;; array literal (TODO: implement memory)");
    (void)node;
}

void WasmTranspiler::visit(ArrayIndexExpression* node) {
    emit("(i32.const 0) ;; array index (TODO: implement)");
    (void)node;
}

void WasmTranspiler::visit(ArrayAssignmentExpression* node) {
    emit(";; array assignment (TODO: implement)");
    (void)node;
}

void WasmTranspiler::visit(LambdaExpression* node) {
    emit(";; lambda (not yet supported in Wasm target)");
    (void)node;
}

void WasmTranspiler::visit(MatchExpression* node) {
    emit(";; match expression (not yet supported in Wasm target)");
    (void)node;
}

void WasmTranspiler::visit(CompoundAssignment* node) {
    if (auto* id = dynamic_cast<Identifier*>(node->target.get())) {
        emit("(local.get $" + id->name + ") ");
        node->value->accept(*this);
        
        if (node->op == "+=") emit(" (f64.add)");
        else if (node->op == "-=") emit(" (f64.sub)");
        else if (node->op == "*=") emit(" (f64.mul)");
        else if (node->op == "/=") emit(" (f64.div)");
        
        emit(" (local.set $" + id->name + ")");
    }
}

void WasmTranspiler::visit(UpdateExpression* node) {
    if (auto* id = dynamic_cast<Identifier*>(node->operand.get())) {
        emit("(local.get $" + id->name + ") (f64.const 1) ");
        emit(node->op == "++" ? "(f64.add)" : "(f64.sub)");
        emit(" (local.set $" + id->name + ")");
    }
}

void WasmTranspiler::visit(InterpolatedString* node) {
    emit("(i32.const 0) ;; interpolated string (TODO)");
    (void)node;
}

// ========================================
// SADK Expression Visitors
// ========================================

void WasmTranspiler::visit(MapLiteral* node) {
    emit("(i32.const 0) ;; map literal (TODO)");
    (void)node;
}

void WasmTranspiler::visit(MemberExpression* node) {
    emit("(i32.const 0) ;; member expression (TODO)");
    (void)node;
}

void WasmTranspiler::visit(SelfExpression* node) {
    emit("(i32.const 0) ;; self (TODO)");
    (void)node;
}

// ========================================
// Statement Visitors
// ========================================

void WasmTranspiler::visit(VariableDeclaration* node) {
    int idx = getLocalIndex(node->name);
    indent();
    emit("(local $" + node->name + " f64)");
    
    if (node->initializer) {
        emit(" ");
        node->initializer->accept(*this);
        emit(" (local.set $" + node->name + ")");
    }
    emit("\n");
}

void WasmTranspiler::visit(ExpressionStatement* node) {
    indent();
    node->expression->accept(*this);
    emit("\n");
}

void WasmTranspiler::visit(BlockStatement* node) {
    emitLine("(block");
    indentLevel++;
    for (const auto& stmt : node->statements) {
        stmt->accept(*this);
    }
    indentLevel--;
    emitLine(")");
}

void WasmTranspiler::visit(IfStatement* node) {
    indent();
    node->condition->accept(*this);
    emit("\n");
    emitLine("(if (then");
    indentLevel++;
    node->thenBranch->accept(*this);
    indentLevel--;
    
    if (node->elseBranch) {
        emitLine(") (else");
        indentLevel++;
        node->elseBranch->accept(*this);
        indentLevel--;
        emitLine("))");
    } else {
        emitLine("))");
    }
}

void WasmTranspiler::visit(WhileStatement* node) {
    emitLine("(block $break");
    indentLevel++;
    emitLine("(loop $continue");
    indentLevel++;
    
    // Condition check
    indent();
    node->condition->accept(*this);
    emit(" (i32.eqz) (br_if $break)\n");
    
    // Loop body
    node->body->accept(*this);
    
    emitLine("(br $continue)");
    indentLevel--;
    emitLine(")");
    indentLevel--;
    emitLine(")");
}

void WasmTranspiler::visit(ForStatement* node) {
    // Convert for loop to while loop structure
    emitLine("(block $break");
    indentLevel++;
    
    // Initializer
    if (node->initializer) {
        node->initializer->accept(*this);
    }
    
    emitLine("(loop $continue");
    indentLevel++;
    
    // Condition
    if (node->condition) {
        indent();
        node->condition->accept(*this);
        emit(" (i32.eqz) (br_if $break)\n");
    }
    
    // Body
    node->body->accept(*this);
    
    // Increment
    if (node->increment) {
        indent();
        node->increment->accept(*this);
        emit("\n");
    }
    
    emitLine("(br $continue)");
    indentLevel--;
    emitLine(")");
    indentLevel--;
    emitLine(")");
}

void WasmTranspiler::visit(BreakStatement*) {
    emitLine("(br $break)");
}

void WasmTranspiler::visit(ContinueStatement*) {
    emitLine("(br $continue)");
}

void WasmTranspiler::visit(FunctionDeclaration* node) {
    // Reset local variable tracking for new function
    localVariables.clear();
    nextLocalIndex = 0;
    inFunction = true;
    
    indent();
    emit("(func $" + node->name + " (export \"" + node->name + "\")");
    
    // Parameters
    for (const auto& param : node->parameters) {
        emit(" (param $" + param + " f64)");
        getLocalIndex(param);
    }
    
    // Result type (assume f64 for all functions with return)
    emit(" (result f64)");
    emit("\n");
    
    indentLevel++;
    
    // Function body
    node->body->accept(*this);
    
    // Default return if not explicit
    emitLine("(f64.const 0)");
    
    indentLevel--;
    emitLine(")");
    emitLine("");
    
    inFunction = false;
}

void WasmTranspiler::visit(ReturnStatement* node) {
    indent();
    if (node->value) {
        node->value->accept(*this);
        emit(" ");
    } else {
        emit("(f64.const 0) ");
    }
    emit("(return)\n");
}

void WasmTranspiler::visit(TryStatement* node) {
    // WebAssembly doesn't have native try/catch
    emitLine(";; try/catch not supported in Wasm - executing try block only");
    if (node->tryBlock) {
        node->tryBlock->accept(*this);
    }
}

void WasmTranspiler::visit(ImportStatement* node) {
    // Imports are handled at module level
    emitLine(";; import: " + node->moduleName);
}

void WasmTranspiler::visit(StructDeclaration* node) {
    emitLine(";; struct " + node->name + " (TODO: implement)");
}
