#!/bin/bash
# SynthFlow Package Manager (sfpm)
# Usage: sfpm <command> [args]

SFPM_VERSION="1.0.0"
SFPM_REGISTRY="https://registry.synthflow.dev"
SFPM_CACHE="$HOME/.sfpm/cache"
SFPM_MODULES="sf_modules"

show_help() {
    echo ""
    echo "SynthFlow Package Manager (sfpm) v$SFPM_VERSION"
    echo ""
    echo "Usage: sfpm <command> [options]"
    echo ""
    echo "Commands:"
    echo "  init                Initialize new SynthFlow project"
    echo "  install [pkg]       Install package(s) from registry"
    echo "  add [pkg]           Alias for install"
    echo "  list, ls            List installed packages"
    echo "  run <script>        Run a script from package.sf"
    echo "  update              Update all packages"
    echo "  version             Show sfpm version"
    echo "  help                Show this help"
    echo ""
    echo "Examples:"
    echo "  sfpm init                    Create new package.sf"
    echo "  sfpm install http            Install http package"
    echo "  sfpm install http json io    Install multiple packages"
    echo "  sfpm run test                Run the \"test\" script"
    echo ""
}

show_version() {
    echo "sfpm v$SFPM_VERSION"
}

cmd_init() {
    echo "Initializing SynthFlow project..."
    
    if [ -f "package.sf" ]; then
        echo "Error: package.sf already exists"
        exit 1
    fi
    
    PROJECT_NAME=$(basename "$PWD")
    
    cat > package.sf << EOF
// SynthFlow Package Configuration
// Generated by sfpm init

{
    "name": "$PROJECT_NAME",
    "version": "1.0.0",
    "description": "A SynthFlow project",
    "main": "main.sf",
    "scripts": {
        "start": "synthflow run main.sf",
        "test": "synthflow run tests/test.sf"
    },
    "dependencies": {},
    "devDependencies": {}
}
EOF

    echo "Created package.sf"
    echo ""
    echo "Next steps:"
    echo "  1. Edit package.sf to configure your project"
    echo "  2. Create main.sf as your entry point"
    echo "  3. Run 'sfpm install <package>' to add dependencies"
    echo ""
}

cmd_install() {
    if [ -z "$1" ]; then
        echo "Installing dependencies from package.sf..."
        echo "No dependencies found in package.sf"
        return
    fi
    
    mkdir -p "$SFPM_MODULES"
    
    for pkg in "$@"; do
        echo "Installing $pkg..."
        
        # Check stdlib
        SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
        if [ -f "$SCRIPT_DIR/stdlib/$pkg.sf" ]; then
            cp "$SCRIPT_DIR/stdlib/$pkg.sf" "$SFPM_MODULES/$pkg.sf"
            echo "Installed $pkg from stdlib"
        elif [ -f "stdlib/$pkg.sf" ]; then
            cp "stdlib/$pkg.sf" "$SFPM_MODULES/$pkg.sf"
            echo "Installed $pkg from local stdlib"
        else
            echo "Package $pkg not found in stdlib"
        fi
    done
}

cmd_list() {
    echo "Installed packages in $SFPM_MODULES:"
    echo ""
    
    if [ ! -d "$SFPM_MODULES" ]; then
        echo "No packages installed yet"
        echo "Run 'sfpm install <package>' to install packages"
        return
    fi
    
    for f in "$SFPM_MODULES"/*.sf; do
        if [ -f "$f" ]; then
            echo "  - $(basename "$f" .sf)"
        fi
    done
    echo ""
}

cmd_run() {
    if [ -z "$1" ]; then
        echo "Error: Script name required"
        echo "Usage: sfpm run <script>"
        return
    fi
    
    echo "Running script: $1"
    
    case "$1" in
        start)
            if [ -f "main.sf" ]; then
                synthflow run main.sf
            else
                echo "Error: main.sf not found"
            fi
            ;;
        test)
            if [ -f "tests/test.sf" ]; then
                synthflow run tests/test.sf
            else
                echo "Error: tests/test.sf not found"
            fi
            ;;
        *)
            echo "Unknown script: $1"
            ;;
    esac
}

cmd_update() {
    echo "Updating packages..."
    echo "All packages are up to date"
}

# Main command dispatch
case "$1" in
    "" | "help" | "--help" | "-h")
        show_help
        ;;
    "version" | "--version" | "-v")
        show_version
        ;;
    "init")
        cmd_init
        ;;
    "install" | "add")
        shift
        cmd_install "$@"
        ;;
    "list" | "ls")
        cmd_list
        ;;
    "run")
        shift
        cmd_run "$@"
        ;;
    "update")
        cmd_update
        ;;
    *)
        echo "Unknown command: $1"
        show_help
        ;;
esac
