@echo off
REM SynthFlow Package Manager (sfpm)
REM Usage: sfpm <command> [args]

setlocal enabledelayedexpansion

set SFPM_VERSION=1.0.0
set SFPM_REGISTRY=https://registry.synthflow.dev
set SFPM_CACHE=%USERPROFILE%\.sfpm\cache
set SFPM_MODULES=sf_modules

if "%1"=="" goto help
if "%1"=="help" goto help
if "%1"=="--help" goto help
if "%1"=="-h" goto help
if "%1"=="version" goto version
if "%1"=="--version" goto version
if "%1"=="init" goto init
if "%1"=="install" goto install
if "%1"=="add" goto install
if "%1"=="list" goto list
if "%1"=="ls" goto list
if "%1"=="run" goto runscript
if "%1"=="update" goto update

echo Unknown command: %1
goto help

:help
echo.
echo SynthFlow Package Manager (sfpm) v%SFPM_VERSION%
echo.
echo Usage: sfpm ^<command^> [options]
echo.
echo Commands:
echo   init                Initialize new SynthFlow project
echo   install [pkg]       Install package(s) from registry
echo   add [pkg]           Alias for install
echo   list, ls            List installed packages
echo   run ^<script^>        Run a script from package.sf
echo   update              Update all packages
echo   version             Show sfpm version
echo   help                Show this help
echo.
echo Examples:
echo   sfpm init                    Create new package.sf
echo   sfpm install http            Install http package
echo   sfpm install http json io    Install multiple packages
echo   sfpm run test                Run the "test" script
echo.
goto end

:version
echo sfpm v%SFPM_VERSION%
goto end

:init
echo Initializing SynthFlow project...

REM Check if package.sf already exists
if exist package.sf (
    echo Error: package.sf already exists
    goto end
)

REM Get project name from current directory
for %%I in (.) do set PROJECT_NAME=%%~nxI

REM Create package.sf
(
echo // SynthFlow Package Configuration
echo // Generated by sfpm init
echo.
echo {
echo     "name": "%PROJECT_NAME%",
echo     "version": "1.0.0",
echo     "description": "A SynthFlow project",
echo     "main": "main.sf",
echo     "scripts": {
echo         "start": "synthflow run main.sf",
echo         "test": "synthflow run tests/test.sf"
echo     },
echo     "dependencies": {},
echo     "devDependencies": {}
echo }
) > package.sf

echo Created package.sf
echo.
echo Next steps:
echo   1. Edit package.sf to configure your project
echo   2. Create main.sf as your entry point
echo   3. Run 'sfpm install ^<package^>' to add dependencies
echo.
goto end

:install
if "%2"=="" (
    echo Installing dependencies from package.sf...
    REM TODO: Parse package.sf and install all dependencies
    echo No dependencies found in package.sf
    goto end
)

echo Installing %2...

REM Create sf_modules directory if it doesn't exist
if not exist %SFPM_MODULES% mkdir %SFPM_MODULES%

REM Check if it's a stdlib module
set STDLIB_PATH=%~dp0stdlib\%2.sf
if exist "%STDLIB_PATH%" (
    echo Copying from stdlib...
    copy "%STDLIB_PATH%" "%SFPM_MODULES%\%2.sf" >nul
    echo Installed %2 from stdlib
    goto installnext
)

REM Check local stdlib
if exist "stdlib\%2.sf" (
    echo Copying from local stdlib...
    copy "stdlib\%2.sf" "%SFPM_MODULES%\%2.sf" >nul
    echo Installed %2 from local stdlib
    goto installnext
)

echo Package %2 not found in stdlib
echo Available stdlib packages: io, json, http, math, string, array, etc.

:installnext
REM Install additional packages if provided
shift
if not "%2"=="" goto install
goto end

:list
echo Installed packages in %SFPM_MODULES%:
echo.
if not exist %SFPM_MODULES% (
    echo No packages installed yet
    echo Run 'sfpm install ^<package^>' to install packages
    goto end
)
for %%f in (%SFPM_MODULES%\*.sf) do (
    echo   - %%~nf
)
echo.
goto end

:runscript
if "%2"=="" (
    echo Error: Script name required
    echo Usage: sfpm run ^<script^>
    goto end
)
echo Running script: %2
REM TODO: Parse package.sf and run the named script
if "%2"=="start" (
    if exist main.sf (
        synthflow run main.sf
    ) else (
        echo Error: main.sf not found
    )
)
if "%2"=="test" (
    if exist tests\test.sf (
        synthflow run tests\test.sf
    ) else (
        echo Error: tests\test.sf not found
    )
)
goto end

:update
echo Updating packages...
REM TODO: Check for package updates
echo All packages are up to date
goto end

:end
endlocal
